#!/usr/bin/env python
"""Regression tests for MODE = QHA beyond the fresh-run coverage of test_zno.py.

Stages (all use the ZnO wurtzite fixture from example/ZnO/qha_relax on a
shortened temperature grid, T = 0..300 K):

1. fresh      : QHA structural optimization (RELAX_STR = 2), h5 output,
                compared against committed references
                (example/ZnO/qha_relax/reference_for_test).
2. restart-h5 : rerun with RESTART_QHA = 1; the state is read back from
                PREFIX.qha.h5 and the regenerated outputs must match the
                fresh run.
3. text-io    : FILE_FORMAT = text fresh run + RESTART_QHA = 1 restart via
                the legacy .renorm_harm_dymat/.V0 files; outputs must match
                the fresh h5 run.
4. ialgo-mpi  : IALGO = 1 (band-parallel V4) on 2 MPI ranks; guards the
                ialgo/selfenergy_offdiagonal broadcasts in
                Qha::exec_qha_optimization (the two V4 kernels issue
                different MPI collectives, so a missing broadcast hangs or
                diverges). Skipped when mpirun is unavailable.
5. perturbative: RELAX_STR = 3 (lowest-order QHA) run, compared against
                committed references.

Run from the build directory: python3 ../test/test_qha.py [--jobs all]
"""

import argparse
import glob
import os
import shutil
import subprocess
import sys
import zipfile

import numpy as np

TEMPERATURE_TAG = "  TMIN = 0\n  TMAX = 300\n  DT = 100\n"

# Files regenerated by every run (loaded state or full loop) and files that
# only the structural-optimization loop writes.
FILES_POSTPROCESS = ["qha_thermo", "V0"]
FILES_RELAX_LOOP = ["atom_disp", "umn_tensor", "normal_disp"]


def isclose(a, b, rel_tol=1e-9, abs_tol=1.0e-12):
    return abs(a - b) <= max(rel_tol * max(abs(a), abs(b)), abs_tol)


def compare_files(file_now, file_ref, rel_tol, abs_tol, label):
    data_ref = np.loadtxt(file_ref, ndmin=2)
    data_now = np.loadtxt(file_now, ndmin=2)

    if data_ref.shape != data_now.shape:
        print(
            "%s: shape mismatch in %s: ref %s vs now %s"
            % (label, file_now, data_ref.shape, data_now.shape)
        )
        return 1

    ok = True
    for i in range(data_ref.shape[0]):
        for j in range(data_ref.shape[1]):
            ok = ok & isclose(data_ref[i, j], data_now[i, j], rel_tol, abs_tol)
    if not ok:
        diff = np.abs(data_now - data_ref)
        idx = np.unravel_index(np.argmax(diff), diff.shape)
        print(
            "%s: mismatch in %s at %s: ref %.16e now %.16e"
            % (label, file_now, str(idx), data_ref[idx], data_now[idx])
        )
        return 1
    return 0


def rewrite_input(template, fname, prefix, extra_general="", extra_qha="",
                  relax_str=None):
    with open(template) as f:
        text = f.read()

    for pattern in ["PREFIX = ZnO_qha", "  TMIN = 0\n  TMAX = 1000\n  DT = 100\n",
                    "MODE = QHA\n", "RESTART_QHA = 0", "RELAX_STR = 2"]:
        if pattern not in text:
            raise RuntimeError(
                "Template %s no longer contains %r" % (template, pattern)
            )

    text = text.replace("PREFIX = ZnO_qha", "PREFIX = %s" % prefix)
    text = text.replace(
        "  TMIN = 0\n  TMAX = 1000\n  DT = 100\n", TEMPERATURE_TAG
    )
    if extra_general:
        text = text.replace("MODE = QHA\n", "MODE = QHA\n  %s\n" % extra_general)
    if extra_qha:
        text = text.replace(
            "RESTART_QHA = 0", "RESTART_QHA = 0\n  %s" % extra_qha
        )
    if relax_str is not None:
        text = text.replace("RELAX_STR = 2", "RELAX_STR = %d" % relax_str)

    with open(fname, "w") as f:
        f.write(text)


def run_anphon(anphonbin, input_file, logfile, nprocs=1, timeout=1800):
    cmd = [anphonbin, input_file]
    if nprocs > 1:
        cmd = ["mpirun", "-np", str(nprocs)] + cmd
    try:
        with open(logfile, "w") as f:
            proc = subprocess.run(cmd, stdout=f, timeout=timeout)
    except subprocess.TimeoutExpired:
        print("Timeout while running %s (suspected MPI hang)" % input_file)
        return 1
    except Exception as e:
        print("Failed to launch %s: %s" % (cmd, e))
        return 1
    if proc.returncode != 0:
        print("anphon exited with code %d for %s" % (proc.returncode, input_file))
        return 1
    return 0


def snapshot(prefix, files, dest):
    os.makedirs(dest, exist_ok=True)
    for suffix in files:
        shutil.copy("%s.%s" % (prefix, suffix), dest)


def stage_fresh(anphonbin, refdir):
    rewrite_input("ZnO_qha_thermo.in", "qha_fresh.in", "ZnO_qha4")
    if run_anphon(anphonbin, "qha_fresh.in", "qha_fresh.log"):
        return 1
    snapshot("ZnO_qha4", FILES_POSTPROCESS + FILES_RELAX_LOOP, "fresh_out")

    # The committed references were generated on a different platform, so the
    # absolute floor must sit above cross-compiler noise on numerically zero
    # entries (symmetry-forbidden displacement components are O(1e-11)).
    info = 0
    for suffix in FILES_POSTPROCESS + FILES_RELAX_LOOP:
        info += compare_files(
            "ZnO_qha4.%s" % suffix,
            os.path.join(refdir, "ZnO_qha4.%s" % suffix),
            rel_tol=1.0e-8,
            abs_tol=1.0e-8,
            label="fresh",
        )
    return info


def stage_restart_h5(anphonbin):
    rewrite_input("ZnO_qha_thermo.in", "qha_restart.in", "ZnO_qha4")
    with open("qha_restart.in") as f:
        text = f.read()
    with open("qha_restart.in", "w") as f:
        f.write(text.replace("RESTART_QHA = 0", "RESTART_QHA = 1"))

    if run_anphon(anphonbin, "qha_restart.in", "qha_restart.log"):
        return 1

    # The restart loads the state from ZnO_qha4.qha.h5 and regenerates the
    # postprocess outputs; they must match the fresh run exactly.
    info = 0
    for suffix in FILES_POSTPROCESS:
        info += compare_files(
            "ZnO_qha4.%s" % suffix,
            os.path.join("fresh_out", "ZnO_qha4.%s" % suffix),
            rel_tol=1.0e-12,
            abs_tol=1.0e-14,
            label="restart-h5",
        )
    return info


def stage_text_io(anphonbin):
    rewrite_input(
        "ZnO_qha_thermo.in",
        "qha_text.in",
        "ZnO_qha4t",
        extra_general="FILE_FORMAT = text",
    )
    if run_anphon(anphonbin, "qha_text.in", "qha_text.log"):
        return 1

    info = 0
    for suffix in FILES_POSTPROCESS + FILES_RELAX_LOOP:
        info += compare_files(
            "ZnO_qha4t.%s" % suffix,
            os.path.join("fresh_out", "ZnO_qha4.%s" % suffix),
            rel_tol=1.0e-10,
            abs_tol=1.0e-12,
            label="text-fresh",
        )
    if info:
        return info

    if not os.path.exists("ZnO_qha4t.renorm_harm_dymat"):
        print("text-io: legacy .renorm_harm_dymat was not written")
        return 1

    with open("qha_text.in") as f:
        text = f.read()
    with open("qha_text_restart.in", "w") as f:
        f.write(text.replace("RESTART_QHA = 0", "RESTART_QHA = 1"))
    if run_anphon(anphonbin, "qha_text_restart.in", "qha_text_restart.log"):
        return 1

    for suffix in FILES_POSTPROCESS:
        info += compare_files(
            "ZnO_qha4t.%s" % suffix,
            os.path.join("fresh_out", "ZnO_qha4.%s" % suffix),
            rel_tol=1.0e-10,
            abs_tol=1.0e-12,
            label="text-restart",
        )
    return info


def stage_ialgo_mpi(anphonbin):
    if shutil.which("mpirun") is None:
        print("ialgo-mpi: mpirun not found, stage skipped")
        return 0

    rewrite_input(
        "ZnO_qha_thermo.in", "qha_ialgo1.in", "ZnO_qha4b", extra_qha="IALGO = 1"
    )
    if run_anphon(anphonbin, "qha_ialgo1.in", "qha_ialgo1.log", nprocs=2):
        return 1

    # IALGO only changes the V4 work distribution; the physics must match
    # the serial IALGO = 0 run to floating-point accumulation accuracy.
    info = 0
    for suffix in FILES_POSTPROCESS + FILES_RELAX_LOOP:
        info += compare_files(
            "ZnO_qha4b.%s" % suffix,
            os.path.join("fresh_out", "ZnO_qha4.%s" % suffix),
            rel_tol=1.0e-6,
            abs_tol=1.0e-8,
            label="ialgo-mpi",
        )
    return info


def stage_perturbative(anphonbin, refdir):
    rewrite_input(
        "ZnO_qha_thermo.in", "qha_pert.in", "ZnO_pqha", relax_str=3
    )
    if run_anphon(anphonbin, "qha_pert.in", "qha_pert.log"):
        return 1

    # Same cross-platform noise floor as the fresh-run comparison.
    info = 0
    for suffix in FILES_POSTPROCESS:
        info += compare_files(
            "ZnO_pqha.%s" % suffix,
            os.path.join(refdir, "ZnO_pqha.%s" % suffix),
            rel_tol=1.0e-8,
            abs_tol=1.0e-8,
            label="perturbative",
        )
    return info


def copy_input_files(workdir, example_dir):
    file_list = [
        "ZnO332_500K_cutoff1208_nbody233.xml.zip",
        "ZnO442_harmonic.xml.zip",
        "ZnO_qha_thermo.in",
    ]
    for file in file_list:
        src = os.path.join(example_dir, file)
        if not os.path.exists(src):
            print("File %s not found in %s" % (file, example_dir))
            return 1
        shutil.copy(src, workdir)

    strain_dir = os.path.join(example_dir, "strain_IFC")
    if not os.path.exists(strain_dir):
        print("Directory strain_IFC not found in %s" % example_dir)
        return 1
    shutil.copytree(
        strain_dir, os.path.join(workdir, "strain_IFC"), dirs_exist_ok=True
    )
    return 0


def uncompress_files(workdir):
    for file in [
        "ZnO332_500K_cutoff1208_nbody233.xml.zip",
        "ZnO442_harmonic.xml.zip",
    ]:
        with zipfile.ZipFile(file, "r") as zip_ref:
            zip_ref.extractall(workdir)
    for file in glob.glob("strain_IFC/*.zip"):
        with zipfile.ZipFile(file, "r") as zip_ref:
            zip_ref.extractall(os.path.join(workdir, "strain_IFC"))
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--jobs", type=str, default="all", help="Job types (all, copy, run)"
    )
    args = parser.parse_args()

    build_dir = os.getcwd()
    project_root = os.path.dirname(build_dir)
    example_dir = os.path.join(project_root, "example/ZnO/qha_relax/")
    refdir = os.path.join(example_dir, "reference_for_test")

    workdir = os.path.join(project_root, "test/qha")
    os.makedirs(workdir, exist_ok=True)
    os.chdir(workdir)

    anphonbin = os.path.join(project_root, "_build/anphon/anphon")

    if args.jobs in ["all", "copy"]:
        if copy_input_files(workdir, example_dir):
            sys.exit(1)
        if uncompress_files(workdir):
            print("Failed to uncompress files")
            sys.exit(1)

    info = 0
    if args.jobs in ["all", "run"]:
        for name, stage in [
            ("fresh", lambda: stage_fresh(anphonbin, refdir)),
            ("restart-h5", lambda: stage_restart_h5(anphonbin)),
            ("text-io", lambda: stage_text_io(anphonbin)),
            ("ialgo-mpi", lambda: stage_ialgo_mpi(anphonbin)),
            ("perturbative", lambda: stage_perturbative(anphonbin, refdir)),
        ]:
            info = stage()
            if info:
                print("ZnO QHA [%s] --> failed" % name)
                sys.exit(1)
            print("ZnO QHA [%s] --> pass" % name)

    print("ZnO QHA --> pass")
    sys.exit(0)
