# Copyright (c) 2023 Ryota Masuki (strainIFCcoupling,
#                    https://github.com/r-masuki/strainIFCcoupling)
# Copyright (c) 2026 Terumasa Tadano
# MIT license.  See LICENCE.txt of the ALAMODE package.
"""Job-script generation.

A job template must contain a line with the token ``RUN_DFT_CALCULATION``;
that line is replaced by a loop over the calculation directories which runs
the lines of the DFT-command file inside each directory (same convention as
the original strainIFCcoupling scripts).
"""

import os
import stat

TOKEN = "RUN_DFT_CALCULATION"


def render_job_script(template_text, dft_command_text, subdirs):
    if TOKEN not in template_text:
        raise ValueError(f"the job template does not contain the token {TOKEN}")
    cmds = [l.rstrip() for l in dft_command_text.splitlines() if l.strip()]
    block = ["for d in " + " ".join(subdirs) + "; do", "  (", '    cd "$d" || exit 1']
    block += ["    " + c for c in cmds]
    block += ["  )", "done"]
    out = []
    for line in template_text.splitlines():
        if TOKEN in line:
            out.extend(block)
        else:
            out.append(line)
    return "\n".join(out) + "\n"


def write_run_all(path, subdirs, dft_command_text=None):
    """Plain shell loop over the directories (used when no template is given)."""
    cmds = (
        [l.rstrip() for l in dft_command_text.splitlines() if l.strip()]
        if dft_command_text
        else ["# put the command that runs the DFT code here"]
    )
    lines = [
        "#!/bin/bash",
        "# generated by ALAMODE strainkit",
        "set -e",
        "for d in " + " ".join(subdirs) + "; do",
        "  (",
        '    cd "$d" || exit 1',
    ]
    lines += ["    " + c for c in cmds]
    lines += ["  )", "done", ""]
    with open(path, "w") as f:
        f.write("\n".join(lines))
    os.chmod(path, os.stat(path).st_mode | stat.S_IXUSR)
